title_name = "Fable II" # 2, GOTY (Game Of The Year)/Platinum Edition
title_id = "4D5307F1" # MS-2033
hash = "4145F96D2DEE2AB5" # default.xex
#media_id = [
#    "1D1F480C", # Disc (Germany):     http://redump.org/disc/61715
#    "51F48E54", # Disc (Italy):       http://redump.org/disc/62006
#    "716F0A0D", # Disc (USA, Europe): http://redump.org/disc/20202
#    "772E8EE8", # Disc (Spain):       http://redump.org/disc/20232
#]

[[patch]]
    name = "60 FPS"
    author = "Margen67"
    is_enabled = false

    [[patch.be8]]
        address = 0x82b9c8eb
        value = 0x01

[[patch]]
    name = "1280x720 Resolution"
    desc = "Original resolution is 1120x720."
    author = "Margen67"
    is_enabled = false

    [[patch.be16]]
        address = 0x8238df5a
        value = 0x0500

[[patch]]
    name = "Disable MSAA (Multi-Sample Anti-Aliasing)"
    author = "Margen67"
    is_enabled = false

    [[patch.be8]]
        address = 0x8238df3f
        value = 0x01

[[patch]]
    name = "Disable Texture Morphing"
    desc = "Prevents the dog & hero's broken textures. Makeup is still bugged. Makes the evil morph strange."
    author = "Guy"
    is_enabled = false

    [[patch.be16]]
        address = 0x8220EF10
        value = 0x4280

[[patch]]
    name = "High Tick Rate"
    desc = "Sets engine tick rate to 30hz, from 15. Makes a smoother expression meter and UI. Causes small side effects."
    author = "Guy"
    is_enabled = false

    [[patch.be32]]
       address = 0x8233aeb4
       value = 0x60000000
    [[patch.be8]]
        address = 0x83319511
        value = 0x3E

[[patch]]
    name = "Unlock Website Items"
    desc = "Unlocks the Guild Chest containing the items that were obtainable from the Fable 2 website."
    author = "Guy"
    is_enabled = false

    [[patch.be8]]
        address = 0x8256e4e3
        value = 0x01
    [[patch.be32]]
        address = 0x8256e4b8
        value = 0x42800028

[[patch]]
    name = "Unlock Collectors Edition Content"
    desc = "Adds Hal's items to the guild chest, and enables the Hall of the Dead dungeon."
    author = "Guy"
    is_enabled = false

    [[patch.be32]]
        address = 0x824B366C
        value = 0x39200001
